server:
  port: 8086

spring:
  application:
    name: notification-service
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP:kafka:9092}
    consumer:
      group-id: notification-service-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

aws:
  endpoint-url: http://${FLOCI_HOST:floci}:4566
  region: ${AWS_REGION:ap-south-1}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
