server:
  port: 8083

spring:
  application:
    name: order-service
  datasource:
    url: jdbc:postgresql://${DB_HOST:postgres-order}:${DB_PORT:5432}/orderdb
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP:kafka:9092}
    admin:
      fail-fast: false
  flyway:
    connect-retries: 15

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  health:
    redis:
      enabled: false
